### PR TITLE
Changed background color that suits the logo

### PR DESCRIPTION
**Pull request by MMaus26**
This is an optional request, because is stays ugly.

### CODE REVIEW

**Comment by Potherca** [comment]
I love it. @Marascon can I get a 👍 ?

**Comment by Marascon** [comment]
Seems fun @dannyverp Can i get an amen!

**Review by Potherca — APPROVED** [review]

**Comment by dannyverp** [comment]
Can't think what might go wrong with this 👍

**Comment by Potherca** [comment]
Screenshot 2019-10-18 at 19 20 00

**Pull request merged**
